"""
Deskew and display OPM data

This file is meant for quick deskew and display of qi2lab OPM results. No deconvolution and it assumes everything fits in memory.
"""

from pathlib import Path
from tqdm import tqdm
import tensorstore as ts
import ndv
from opm_processing.imageprocessing import deskew, downsample_axis

def deskew_and_display(root_path: Path):
    """Deskew, downsample by 2x in Z, and display OPM data.
    
    This code assumes data is generated by opm-v2 GUI and the resulting data is 
    saved using OPMMirrorHandler. All revelant metadata is read from imaging files, 
    including stage transformation, camera parameters, and channels. 
    
    Parameters
    ----------
    root_path: Path
    """
    
    spec = {
        "driver" : "zarr",
        "kvstore" : {
            "driver" : "file",
            "path" : str(root_path)
        }
    }
    datastore = ts.open(spec)
    print(datastore.spec())


if __name__ == "__main__":
    root_path = Path(r"/mnt/opm3/20250225_opm/isolated_beads_002.zarr")
        
    deskew_and_display(root_path)